### ISSUE TITLE
IndexedTriangleStripSet misrendered

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#599]
Navigate to http://www.jishop.com/temp/x3d/#SimpleIndTriStrip .  X3DOM only renders one triangle, even though the scene contains two.

The geometry goes:

&lt;IndexedTriangleStripSet index="1 2 0 3" solid="false"&gt;
       &lt;Coordinate point="0 1 0 0 0 -1 -1 0 0 0 0 1"/&gt;
&lt;/IndexedTriangleStripSet&gt;

The offending X3D file is attached (renamed to .TXT).

[SimpleIndTriStrip.x3d.txt](https://github.com/x3dom/x3dom/files/92221/SimpleIndTriStrip.x3d.txt)

**Comment by YuanxiangFranck** [comment]
The problem is really dumb, IndexedTriangleStrip should end with -1 (it is the separator in case of multiple triangle strip).
The solution : 
<IndexedTriangleStripSet index="1 2 0 3 -1" solid="false">

**Comment by YuanxiangFranck** [comment]
I send a pull request for the fix, can you close the issue?

**Comment by sevaa** [comment]
It should not. Quoting the standard:

"The last strip may be (but does not have to be) followed by a "−1"."

It's a bug.

**Comment by YuanxiangFranck** [comment]
yes I know and I fixed it and send the pull request ;)

**Comment by sevaa** [comment]
The linked example still shows only one triangle. Not fixed.

**Comment by bhaettasch** [comment]
Maybe you tried it before the daily build process run.

Now there are two triangles:

![triangle_strip](https://cloud.githubusercontent.com/assets/6319964/12640161/d5ac3d18-c5a8-11e5-91ae-61b9217d87ea.png)

**Comment by sevaa** [comment]
Confirmed.
